/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastructurefinalproject;

import java.io.File;
import java.nio.charset.Charset;
import java.util.Arrays;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mohammadi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        new Tools().setCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChoseFile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpbPro = new javax.swing.JProgressBar();
        btnPrintTree = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChoseFile.setText("Choose File");
        btnChoseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseFileActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(68, 94, 119));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 234, 233));
        jLabel1.setText("Ali reza / Khesraw Huffman Coding Project");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpbPro.setValue(1);

        btnPrintTree.setText("Print Tree");
        btnPrintTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintTreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpbPro, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPrintTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChoseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChoseFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpbPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrintTree)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static int removeDuplicateCharacterFromArray(char array[], int n) {
        if (n == 0 || n == 1) {
            return n;
        }
        char[] temp = new char[n];
        int j = 0;
        for (int i = 0; i < n - 1; i++) {
            if (array[i] != array[i + 1]) {
                temp[j++] = array[i];
            }
        }
        temp[j++] = array[n - 1];
        
        for (int i = 0; i < j; i++) {
            array[i] = temp[i];
        }
        return j;
    }
    HuffmanNode root;
    File selectedFile = null;
    JFrame mainFrame = this; 
    private void btnChoseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseFileActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Open (*cmp,*.txt) Files");

        //----------------------------- Extension Filter -----------------------------------------------------------------------------------------------------------------
        FileNameExtensionFilter txt = new FileNameExtensionFilter("TEXT(*.txt)", "txt");
        FileNameExtensionFilter cmp = new FileNameExtensionFilter("cmp(*.cmp)", "cmp");
        
        file.setFileFilter(txt);
        file.setFileFilter(cmp);

        //------------------------- Set Default Directory --------------------------------------------------------------------------------------------------------------------------------------------
        File defaultDirectory = new File(System.getProperty("user.home") + System.getProperty("file.separator") + "Desktop");
        file.setCurrentDirectory(defaultDirectory);
        
        file.showOpenDialog(this);
        selectedFile = file.getSelectedFile();
        
        String selectedFilePath = selectedFile.getPath();
        String extention = selectedFilePath.substring(selectedFilePath.lastIndexOf("."), selectedFilePath.length());
        
        Tools tools = new Tools();
        
        String text = "";
        
        if (extention.equals(".txt")) 
        {
            text = tools.readWholeTextFromFile(selectedFile);
            char[] charArray = tools.getCharacterArrayFromText(text);
            int length = charArray.length;
            int[] letterFrequency = tools.getLetterFrequency(charArray);
            
            Arrays.sort(charArray);
            
            length = removeDuplicateCharacterFromArray(charArray, length);
            
            root = tools.createTree(length, charArray, letterFrequency);
            Map<Character, String> mp = tools.getHuffmanCodePerCharacter(root, "");
            
            String allBits = tools.getHuffmanCodeAllCharacter(text.toCharArray(), mp);
            
            byte[] bin = allBits.getBytes();
            
            new Thread(new Runnable()
            {
                @Override
                public void run() 
                {
                    try 
                    {
                        for(int i = 1; i <= 100;i+=10)
                        {
                            Thread.sleep(100);
                            jpbPro.setValue(jpbPro.getValue() + i);
                        }
                        file.setSelectedFile(new File("*.cmp"));
                        file.showSaveDialog(mainFrame);
                        File descFile = file.getSelectedFile();
                        String saveDescPath = descFile.getPath();
                        tools.writeCmpFile(saveDescPath, letterFrequency, bin);
                        
                    } catch (InterruptedException ex) 
                    {
                        System.out.println(ex.getMessage());
                    }
                }
            }).start();
            
            

            
        } else if (extention.equals(".cmp")) 
        {
            String treeDataFromCmpFile = tools.readTreeFromCmpFile(selectedFilePath);
            char[] characterArrayLetterFromCmpFile = tools.getTreeLetter(treeDataFromCmpFile);
            int[] characterArrayLetterFrequencyFromCmpFile = tools.getTreeLetterFrequency(treeDataFromCmpFile);
            root = tools.createTreeFromCmpFileData(characterArrayLetterFromCmpFile.length, characterArrayLetterFromCmpFile, characterArrayLetterFrequencyFromCmpFile);
            
            byte[] bb = tools.readHuffmanCodeFromCmpFile(selectedFilePath);
            String myS = new String(bb,Charset.forName("UTF-8"));
            String origanalString = tools.decode(myS, root);
            
            new Thread(new Runnable()
            {
                @Override
                public void run() 
                {
                    try 
                    {
                        for(int i = 1; i <= 100;i+=10)
                        {
                            Thread.sleep(100);
                            jpbPro.setValue(jpbPro.getValue() + i);
                        }
                        file.setSelectedFile(new File("*.txt"));
                        file.showSaveDialog(mainFrame);
                        File descFile = file.getSelectedFile();
                        String saveDescPath = descFile.getPath();
                        tools.writeTextFile(saveDescPath, origanalString);
                    } catch (InterruptedException ex) 
                    {
                        System.out.println(ex.getMessage());
                    }
                }
            }).start();
            
            
            
            
        }
        

    }//GEN-LAST:event_btnChoseFileActionPerformed

    private void btnPrintTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintTreeActionPerformed
        TreePrinter t = new TreePrinter();
       t.print(root);
    }//GEN-LAST:event_btnPrintTreeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoseFile;
    private javax.swing.JButton btnPrintTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jpbPro;
    // End of variables declaration//GEN-END:variables
}
